apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: appsmith-gateway
  namespace: appsmith
spec:
  gatewayClassName: traefik
  listeners:
  - name: websecure
    protocol: HTTPS
    port: 8443
    hostname: appsmith.freecodecamp.net
    tls:
      mode: Terminate
      certificateRefs:
      - name: appsmith-tls-cloudflare
    allowedRoutes:
      namespaces:
        from: Same
  - name: web
    protocol: HTTP
    port: 8000
    hostname: appsmith.freecodecamp.net
    allowedRoutes:
      namespaces:
        from: Same
