apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: n8n-gateway
  namespace: n8n
spec:
  gatewayClassName: traefik
  listeners:
  - name: websecure
    protocol: HTTPS
    port: 8443
    hostname: n8n.freecodecamp.net
    tls:
      mode: Terminate
      certificateRefs:
      - name: n8n-tls-cloudflare
    allowedRoutes:
      namespaces:
        from: Same
  - name: web
    protocol: HTTP
    port: 8000
    hostname: n8n.freecodecamp.net
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: webhooks-gateway
  namespace: n8n
spec:
  gatewayClassName: traefik
  listeners:
  - name: websecure
    protocol: HTTPS
    port: 8443
    hostname: n8n-wh.freecodecamp.net
    tls:
      mode: Terminate
      certificateRefs:
      - name: n8n-tls-cloudflare
    allowedRoutes:
      namespaces:
        from: Same
  - name: web
    protocol: HTTP
    port: 8000
    hostname: n8n-wh.freecodecamp.net
    allowedRoutes:
      namespaces:
        from: Same
