apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: n8n
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: n8n
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-http-redirect
  namespace: n8n
spec:
  parentRefs:
  - name: n8n-gateway
    namespace: n8n
    sectionName: web
  hostnames:
  - n8n.freecodecamp.net
  rules:
  - filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: redirect-https
    backendRefs:
    - name: n8n-main
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: n8n-main-route
  namespace: n8n
spec:
  parentRefs:
  - name: n8n-gateway
    namespace: n8n
    sectionName: websecure
  hostnames:
  - n8n.freecodecamp.net
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: secure-headers
    backendRefs:
    - name: n8n-main
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webhooks-http-redirect
  namespace: n8n
spec:
  parentRefs:
  - name: webhooks-gateway
    namespace: n8n
    sectionName: web
  hostnames:
  - n8n-wh.freecodecamp.net
  rules:
  - filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: redirect-https
    backendRefs:
    - name: n8n-main
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webhooks-route
  namespace: n8n
spec:
  parentRefs:
  - name: webhooks-gateway
    namespace: n8n
    sectionName: websecure
  hostnames:
  - n8n-wh.freecodecamp.net
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ExtensionRef
      extensionRef:
        group: traefik.io
        kind: Middleware
        name: secure-headers
    backendRefs:
    - name: n8n-main
      port: 80
