apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus

resources:
- namespace.yaml
- tailscale-ingress.yaml

secretGenerator:
- name: alertmanager-webhook-urls
  envs:
  - secrets/.secrets.env

generatorOptions:
  disableNameSuffixHash: true
