apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appsmith-data
  namespace: appsmith
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
