services:
  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:80"
    volumes:
      - ./data/stacks:/appsmith-stacks
    environment:
      - APPSMITH_ENCRYPTION_PASSWORD=${APPSMITH_ENCRYPTION_PASSWORD}
      - APPSMITH_ENCRYPTION_SALT=${APPSMITH_ENCRYPTION_SALT}
      - APPSMITH_SUPERVISOR_PASSWORD=${APPSMITH_SUPERVISOR_PASSWORD}
