---
collections:
  - name: community.general
    version: ">=10.0.0,<13.0.0"
  - name: community.docker
    version: ">=3.0.0,<5.0.0"
  - name: community.digitalocean
    version: ">=1.27.0,<2.0.0"
  - name: ansible.posix
    version: ">=2.0.0,<3.0.0"
  - name: grafana.grafana
    version: ">=5.7.0,<6.0.0"
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: 1.1.1

roles:
  - name: rolehippie.rclone
    version: "v2.8.1"
