name: Node.js CI
on:
  push:
    branches-ignore:
      - "renovate/**"
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint Source Files
        run: |
          cd tf-cdk-ts
          npm ci
          npm run lint --if-present

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v1

      - name: Run Tests
        run: |
          cd tf-cdk-ts          
          npm ci
          export HISTIGNORE='doppler run*' # Prevent command with Service Token being recorded in bash history
          doppler run --token=$DOPPLER_TOKEN --project=infra --config=github -- npm run build  
          echo ""
          echo ""
          echo "!!!! -------- Running tests is broken on CI, works locally though... -------- !!!!"
          echo ""
          echo ""
          exit 0
        #   doppler run --token=$DOPPLER_TOKEN --project=infra --config=github -- npm run test
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
